### ISSUE TITLE
Variant

### ISSUE THREAD

**Issue by phil-s** [davep/goto-line-faster.el#1] opened 2020-09-02 01:33 UTC
I really like this idea; thanks for sharing!

I rewrote it for myself as follows, if it's of any interest.

```lang-el
;; Make "M-g [1-9] ... RET" a shortcut for "M-g g [1-9] ... RET"
(dotimes (n 9)
  (global-set-key (kbd (format "M-g %s" (1+ n))) #'my-goto-line))

(defun my-goto-line (&optional buffer)
  "Slightly faster `goto-line' for interactive use."
  (interactive "P")
  (when (and (>= last-command-event ?1)
             (<= last-command-event ?9)
             (not (numberp current-prefix-arg)))
    (push last-command-event unread-command-events))
  (call-interactively #'goto-line))
```

(Not really an "issue" sorry; not sure how else to just comment...)

**Comment by davep** [comment] 2020-09-02 06:04
No need to apologise. I'm interested in a different/better approach. What's the thinking behind the difference?

**Comment by phil-s** [comment] 2020-09-02 07:06
Mostly to reduce it to a single command, rather than defining nine different commands plus a generator function.  It seemed a bit cleaner to me.

There's little practical difference.  The main one is that I've supported the prefix argument behaviour of `goto-line`.  This is mostly just for the `C-u M-g ...` behaviour (as numeric prefix args are just another way of specifying the line number, so you wouldn't expect them to be used here).

Otherwise, there's a minor benefit in how these are displayed:
```
Global Bindings Starting With M-g:

key             binding
---             -------
M-g TAB		move-to-column
M-g ESC		Prefix Command
M-g 1 .. M-g 9	my-goto-line
M-g c		goto-char
M-g g		goto-line
M-g n		next-error
M-g p		previous-error
```

**Comment by davep** [comment] 2020-09-02 07:11
Ahh hah! Nice. That does seem more tidy. I was going for a collection of
tidy docstrings but this makes far more sense.

Did you want to spin up a package based on this approach, or would you like
I steal this with proper attribution?

**Comment by phil-s** [comment] 2020-09-02 07:12
Steal away!

**Comment by phil-s** [comment] 2020-09-02 07:32
Note that you *can* still have a dynamic docstring if you want.  I'm not sure whether it's as sensible when the command is also telling you "It is bound to M-g 9, M-g 8, M-g 7, M-g 6, M-g 5, M-g 4, M-g 3, M-g 2, M-g 1.", however you could play with something like the following:

```lang-el
(put 'my-goto-line 'function-documentation
     '(if (and (eq this-command 'describe-key)
               (numberp last-input-event)
               (>= last-input-event ?1)
               (<= last-input-event ?9))
          (format "`goto-line' with pre-populated interactive input %c."
                  last-input-event)
        "`goto-line' with optional pre-populated interactive input."))
```

That's only lightly tested, but should cover `C-h k M-g [1-9]` and provide a generic value otherwise.

I don't think I'm going to bother with this personally.  My gut feeling is that it's more sensible to just have a static docstring which describes how it behaves in general -- which the user can easily correlate with the list of key sequences that it's bound to.

**Comment by phil-s** [comment] 2020-09-02 07:36
Which reminds me... in case you didn't know -- your original code also used the `function-documentation` symbol property, but you could have just passed the docstring directly to `defalias`.

**Comment by davep** [comment] 2020-09-02 08:36
No, you're absolutely right, this approach makes far more sense (the whole docstring thing was sort of caused by me viewing/testing what I was doing via `counsel-M-x`, before I'd actually bound anything). Pretty much what I arrived at was a quick hack to solve a really annoying muscle memory problem I was having and not a lot of thought was given to it.

Your approach is far cleaner and makes much more sense.

Good catch on the docstring thing for `defalias` too. Can you tell I sort of rushed the whole thing?

I was actually going to write up the whole background to this as a blog post, and your adding to this makes it even more worthy of writing up, I think. (all goes back to the very late 1980s and [QEdit](https://en.wikipedia.org/wiki/The_SemWare_Editor#Qedit))

**Comment by phil-s** [comment] 2020-09-02 10:33
Nice :)

My only other suggestion is to drop the `bind-key` dependency -- I think it's excessive to potentially cause people to install and load that package all for the sake of a single line of code.  (I *suspect* the `bind-key` package is mostly intended for people to use in their init files and custom code?)

In any case, that's the only thing preventing this from being a stand-alone library.

**Comment by davep** [comment] 2020-09-02 10:39
Ahh, yeah, good point. I've always liked `bind-key`, ever since I became a heavy `use-package` user; but in the unlikely event that anyone else ends up using this I guess it doesn't make sense to require it. More out of habit than anything else.

**Comment by davep** [comment] 2020-09-16 15:12
Going to close this as I think we're all good with this. Thanks again for your input and advice Phil -- much appreciated.

**Closed as completed by davep** 2020-09-16 15:12 UTC
